services:
  kkphim:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kkphim-web
    ports:
      - "1999:1999"
    environment:
      NODE_ENV: production
      PORT: 1999
      HOSTNAME: 0.0.0.0
    restart: unless-stopped
